#!/bin/bash
# Nagios Check fuer doppelte IPs in der wimport_data
# Jan Weiher, Netcologne Schulsupport <jweiher@netcologne.de>

EXIT_OK=0
EXIT_WARNING=1
EXIT_CRITICAL=2
EXIT_UNKNOWN=3

WIMPORTDATA="/rembo/server/files/global/wimport_data"
if [ ! -f "$WIMPORTDATA" ]; then
	echo "wimport_data not found!"
	exit $EXIT_UNKNOWN
fi

if [ "$(cat $WIMPORTDATA | cut -d ";" -f 5 | grep -v ^# | sort | uniq -d)" == "" ]; then
	echo "OK - no duplicate IPs"
	exit $EXIT_OK
fi

echo "CRITICAL - duplicate IPs found!"
exit $EXIT_CRITICAL
